### PR TITLE
Truncated ellipsoid LV inflation - KCL benchmark problem 2

### PR DESCRIPTION
**Pull request by jennyhelyanwe**
Tracker Item 3876. Problem 2. 

Inflation of a 16 by 16 by 2 truncated ellipsoid model of the LV by 10 kPa, using transversely isotropic Guccione constitutive model. Matlab code is used to generate reference model. Spatial convergence code also included, but is not run during testing.

### CODE REVIEW

**Comment by jennyhelyanwe** [comment]
Hi Chris,

I've added the reference geometry and expected results, also updated the json file. I'm a bit unsure about whether the json file is written correctly. Could you have a look for me?

**Comment by chrispbradley** [comment]
@jennyhelyanwe Are you trying to make this a testing example? If so, then you need to add some more to the json file. Have a look at http://cmiss.bioeng.auckland.ac.nz/OpenCMISS/doc/programmer/local-examples.html. You will also need to have some expected results files to compare against.

**Comment by jennyhelyanwe** [comment]
@chrispbradley Reduced mesh resolution, now takes 5 minutes and 40 seconds to run. Also added a displacement expect result and updated the json file accordingly. Also removed matlab related files since they aren't called anymore. I'll work on converting the matlab files to python scripts and look into committing these later on.

**Comment by chrispbradley** [comment]
@jennyhelyanwe Looks good. I'll pull it in now and you can commit additions later if you like. Don't forget to update any trackers and reference this pull request etc.

**Pull request merged**
