### PR TITLE
Preparation for example migration

### PR DESCRIPTION
**Pull request by rondiplomatico**
Chris,

please revise and merge this update.
It's basically just checking if the NOMPIMOD flag is set, and does not include the mpi.mod file but uses the (fallback) mpi.h header. This is necessary e.g. on windows with pre-compiled MPICH libraries.

This is not intended to be developed any further w.r.t. to this examples repo. this will merely make it easy for me to keep the separate example repos under OpenCMISS-Examples up to date.

### CODE REVIEW

**Comment by chrispbradley** [comment]
@rondiplomatico I culled a few old examples during the last lot of changes. These examples have now being added back in. Could you remove the 42TestingPoints examples from this request?

**Comment by rondiplomatico** [comment]
sure thing, but please clarify. all of them?
they're still included in the current master branch which i based this update on.

**Comment by chrispbradley** [comment]
Hmmm, I thought I did delete them in my branch but clearly something has gone a miss as they are still in the trunk. Ignore above, I'll clean them up later.

**Comment by rondiplomatico** [comment]
so then this can be merged and you'll ditch the 42testingpoints examples then, right?

**Comment by chrispbradley** [comment]
Yip.

**Pull request merged**
